"""empty message

Revision ID: 2c1e87af63e1
Revises: c9310f6395b0
Create Date: 2018-10-17 06:04:40.690513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c1e87af63e1'
down_revision = 'c9310f6395b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visibility', sa.String(length=8), server_default='public', nullable=True))
    op.drop_column('projects', 'visibilty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visibilty', mysql.VARCHAR(length=8), server_default=sa.text("'public'"), nullable=True))
    op.drop_column('projects', 'visibility')
    # ### end Alembic commands ###
