"""empty message

Revision ID: 4d46508d6f79
Revises: f31be164de1a
Create Date: 2018-10-17 05:09:00.846355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d46508d6f79'
down_revision = 'f31be164de1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sponsors')
    op.drop_column('projects', 'visibilty')
    op.drop_column('projects', 'locked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('visibilty', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('projects', sa.Column('sponsors', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
