"""empty message

Revision ID: 4fb59fe2de4d
Revises: e53179f27789
Create Date: 2018-10-17 05:03:08.176358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb59fe2de4d'
down_revision = 'e53179f27789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('locked', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('sponsors', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('visibilty', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visibilty')
    op.drop_column('projects', 'sponsors')
    op.drop_column('projects', 'locked')
    # ### end Alembic commands ###
