"""empty message

Revision ID: bbe88fd736ae
Revises: 4fb59fe2de4d
Create Date: 2018-10-17 05:05:02.049221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe88fd736ae'
down_revision = '4fb59fe2de4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sponsors')
    op.drop_column('projects', 'locked')
    op.drop_column('projects', 'visibilty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visibilty', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('projects', sa.Column('locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('sponsors', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
