"""empty message

Revision ID: c9310f6395b0
Revises: 4d46508d6f79
Create Date: 2018-10-17 05:09:08.870339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9310f6395b0'
down_revision = '4d46508d6f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('locked', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('projects', sa.Column('sponsors', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('visibilty', sa.String(length=8), server_default='public', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visibilty')
    op.drop_column('projects', 'sponsors')
    op.drop_column('projects', 'locked')
    # ### end Alembic commands ###
