"""empty message

Revision ID: e53179f27789
Revises: 
Create Date: 2018-10-16 22:24:31.360813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53179f27789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_author'), 'projects', ['author'], unique=False)
    op.create_index(op.f('ix_projects_date'), 'projects', ['date'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=True)
    op.create_index(op.f('ix_projects_views'), 'projects', ['views'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_views'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_author'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
